name: Monitor new Git versions

on:
  workflow_dispatch:
  # schedule:
  #  # Run this Action every day at 7:37am UTC
  #  - cron: "37 7 * * *"

jobs:
  monitor-git-release:
    runs-on: ubuntu-latest
    steps:
      - uses: git-for-windows/rss-to-issues@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          feed: https://github.com/quic-go/quic-go/releases.atom
          prefix: "[Git]"
          character-limit: 255
          dry-run: true
          labels: github/release,repo/kubernetes/kubernetes,automated-issue
